#!/bin/sh

set -e

sed -n -r '/\/csgillespie\/travis-examples\/tree\// {s/^.*\/csgillespie\/travis-examples\/tree\/([^)]+).*$/\1/;p}' README.md | sort > dirs-in-readme
find * -maxdepth 0 -type d | sort > dirs-in-repo
if ! diff dirs-in-readme dirs-in-repo; then
  echo "$0: Please include a reference to each example in the README.md" >> /dev/stderr
  exit 1
fi

if find * -mindepth 1 -name README.md -exec grep "Build Status" \{\} \+ | egrep -v "^([^/]+)/.*branch=\1"; then
  echo "$0: Please ensure correctness of the build status icon in all sub-README.md" >> /dev/stderr
  exit 1
fi
